name: linting

on:
  pull_request:
    branches: ["main", "develop"]

  workflow_dispatch:

jobs:
  linting:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10

      - name: Install Node.js dependencies
        run: npm install

      - name: Run linting
        uses: wearerrequired/lint-action@v2
        with:
          eslint: true
          prettier: true
